version: '3.1'
services:
  orange:
    image: orange
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    environment:
      TZ: America/Sao_Paulo
    ports:
      - "8080:8080"
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - api-orange
  db:
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: api_orange
    ports:
      - "3306:3306"
    networks:
      - api-orange
networks:
  api-orange:
    driver: bridge
